### ISSUE TITLE
`Class FIFinderSyncExtensionHost is implemented in both ` error occured after select file.

### ISSUE THREAD

**Issue by lidaling** [sqweek/dialog#43] opened 2020-02-24 08:50 UTC
```
objc[35224]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8eddf210) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x14c3fdc8). One of the two will be used. Which one is undefined.
```

**Comment by sqweek** [comment] 2020-03-04 03:24
Duplicate of #24. It's not clear to me that I can do anything about this.

**Closed by sqweek** 2020-03-04 03:24 UTC
